### ISSUE TITLE
Rename `Parser`

### ISSUE THREAD

**Issue by no-reply** [curationexperts/darlingtonia#26]
"Parser" is already proving to be a slightly unwieldy name. We chose this name to differentiate from an `Importer` and "parser" seemed viable given that examples read (parsed) records from a manifest file. However, the `laevigata` importer will *not* parse records from a manifest, but instead draw them from a live Fedora 3 instance.

In this case, the job of the so-called `Parser` is to provide a stream of mapped and validated `InputRecord` objects to the `Importer`. It turns out that "parsing" is an implementation detail.

Perhaps `RecordStream`?

 I don't expect major Parser API changes to accompany any name change. We'll need to deprecate the old class names for removal in 2.0.0, however.

**Comment by mark-dce** [comment]
I'm not sure I see how the source of the records would be relevant here.  In my mind, mapping is one component of parsing and I don't think what you're describing is outside the merriam-webster definition of parsing - see especially 2. in https://www.merriam-webster.com/dictionary/parse.  From a computer science standpoint a mapper seems like the simplest form of parser "a software component that takes input data (frequently text) and builds a data structure" - https://en.wikipedia.org/wiki/Parsing#Parser.

I'm fine with the idea that the input to a "parser" would be a "record steam" which might take the form of a manifest file or output from one or more calls to an API.    If the term "mapper" feels more comfortable than parser, that seems fine too.  In nearly all cases there will need to be some form of transformation (minute inspection, parsing) from source system to target system (mapping).

The main problem I see is that you've said the source is specifically a file https://github.com/curationexperts/darlingtonia/blob/eadd7f2cc89679a7fb754ad5e06089bf2ae2ceef/lib/darlingtonia/parser.rb#L7-L8 - and I think we might want to generalize this to "input stream" - which could be a file, or push, or pull APIs.

On a different tangent, I'm a little anxious about the idea of building our importer to read live from the Emory Fedora.  We can'd be sure what kinds of security, connectivity, and throughput issues we might face when trying to read outside of their datacenter in bulk.  I was envisioning a two step process where we exported the content (possibly via FOXML exports, or some other serialization) to make a static external copy of the content which we could run import tests on multiple times.  I would strongly prefer a process that minimized the number of total times we had to have live interactions with Emory's existing Fedora 3.
